apiVersion: v1
kind: Pod
metadata:
  name: my-pod-new
spec:
  containers:
    - name: my-container
      image:  nginx:latest
      ports:
        - containerPort: 80
      env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: db-username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: db-password
